### ISSUE TITLE
Cancel identifier for DSS-profiles

### ISSUE THREAD

**Issue by martin-lindstrom** [elegnamnden/technical-framework#13]
See https://forum.eidasweb.se/showthread.php?tid=20&pid=109#pid109.

A cancel identifier (http://id.elegnamnden.se/sig-status/1.0/user-cancel) should be introduced to enable a SP to receive information about that a user cancelled user signature operation.

**Comment by Razumain** [comment]
There should be 2 updates:
Section 2.2.2 of ELN-0607 - Implementation Profile for using DSS in Central Signing Services.md

- Change document cross reference from "3.1.5 of [Eid-Registry], SHOULD be used" to "3.1.7 of [Eid-Registry], SHOULD be used"

Section 3.1.7 of ELN-0603 - Registry for Identifiers.md

- Add new identifier for error code for cancel. ("http://id.elegnamnden.se/sig-status/1.0/cancelled-by-user")
