### ISSUE TITLE
Use appropriate example URI:s

### ISSUE THREAD

**Issue by Razumain** [elegnamnden/technical-framework#27]
In the deployment profile, section 6.2, the domain "company.com" as an example of an identifier.

"<saml2:AuthenticatingAuthority>http://idp.company.com/auth</saml2:AuthenticatingAuthority>"

It is inappropriate to use domain names that are in use as real domains. Example domains such as "example.com" should be used instead.

**Comment by martin-lindstrom** [comment]
Solved in https://github.com/elegnamnden/technical-framework/pull/35.
