### ISSUE TITLE
Adding "typ" claim to SAD tokens

### ISSUE THREAD

**Issue by Razumain** [elegnamnden/technical-framework#32]
A new best practice recommendation for JWT suggests that JWT should include a type taclaration using the "typ" claim. This reduce the risk that one JWT of a particular type is mistaken for a JWT of another type. It is therefore suggested to add a "typ" claim to the SAD JWT, defining it to be a SAD token.

**Comment by Razumain** [comment]
See section 3.9 of https://tools.ietf.org/html/draft-sheffer-oauth-jwt-bcp-01

**Comment by martin-lindstrom** [comment]
Solved in PR https://github.com/elegnamnden/technical-framework/pull/30.
