### ISSUE TITLE
Dedikerad felkod för PossibleFraudDetected?

### ISSUE THREAD

**Issue by martin-lindstrom** [elegnamnden/technical-framework#4]
Som ni säkert känner till så lurar bedragare (t.ex. inom fondförvaltning) användare via telefon genom att be dessa knappa in sin PIN-kod för Mobilt BankID, och bedragaren som startat en BankID autentisering mot en tjänst kan då loggas in.

Det finns två huvudsakliga "attacker". I den ena loggar också användaren in, och då kan vissa fel mottas från BankID (typ, "du har redan en pågående inloggning"), och i den andra utför bara bedragaren en inloggning (och användaren ger bara sin PIN-kod). Den sistnämnda är den vanligaste, och också den som är svårast att skydda sig emot. 

Hur en IdP skyddar sig täcks inte av Tekniskt ramverk, men det finns en starkt behov från myndigheter att notifieras om ett möjligt pågående bedrägeriförsök. Mitt förslag är därför att Tekniskt ramverk definierar en ny SAML-felkod, t.ex., http://id.elegnamnden.se/status/1.0/possibleFraud, vilken ska kunna användas för att indikera detta beteende. Felkoden används som en "sub"-felkod, vilket inte borde innebära problem för SP-instanser som använder hyllprodukter som inte förstår denna felkod.

SAML-profiler som används bl.a. i UK använder detta förfarande.

Vad tycker ni?

**Comment by MagnusAnvill** [comment]
Den sistnämnda attacken är som sagt svår att skydda sig emot. Ett motmedel som förvisso eventuellt begränsar "användarupplevelsen" eller möjlighet att logga in på olika sätt, är att bara tillåta inloggning/underskrift med BankID på "denna enhet".

Förslaget ovan är generellt bra anser jag. Dock finns det en liten risk för "false positives" t.ex. om användaren skulle strula med två flikar eller påbörja inloggning, backa i webbläsaren och logga in igen.

**Comment by martin-lindstrom** [comment]
Jo, utan att gå in på BankID-specifika detaljer, så har vi ju ändå problemet med "false positives". Ett alternativ vore ju att utfärda en Assertion, men att inkludera "varnings-attribut" eller liknande i assertion och överlåta till SP:n att ta ställning.
