### ISSUE TITLE
Swedish to eIDAS LoA mapping requires a new identifier for eIDAS low-notified

### ISSUE THREAD

**Issue by Razumain** [elegnamnden/technical-framework#43]
The eIDAS regulation allow notification of eID schemes at Assurance level Low.

Implementation of mapping logic has demonstrated that we need to define Swedish eDIAS identifier for LoA low with notified eID in the same manner as we have provided for level substantial and high.

Not doing so would require us to apply a completely different logic for mapping eIDAS low compared to what is used for eIDAS substantial and high. Making implementations complex and prone to generate errors.

**Comment by Razumain** [comment]
In additional to this, add as comment a reference to the new eIDAS LoA identifiers for NotNotified eID schemes:

- http://eidas.europa.eu/LoA/NotNotified/low
- http://eidas.europa.eu/LoA/NotNotified/substantial
- http://eidas.europa.eu/LoA/NotNotified/high

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/elegnamnden/technical-framework/pull/44.
