### ISSUE TITLE
Extend requirements for MDUI

### ISSUE THREAD

**Issue by martin-lindstrom** [elegnamnden/technical-framework#49]
Section 2 of the "Deployment Profile for the Swedish eID Framework" lists a number of requirements for the inclusion of a `<mdui:UIInfo>` element. We should update this section and be more clear about things like logotypes (transparent, vector based) etc.

**Comment by magnussuther** [comment]
Regarding `<mdui:Logo>`, the documentation should also state that `data:` URIs in its various forms are accepted.

**Comment by martin-lindstrom** [comment]
Since the technical framework is a generic profile we add explicit requirements regarding logo sizes etc. as requirements for the Sweden Connect-federation.
