### ISSUE TITLE
Det är viktigt att svenska export företag har möjlighet att lämna e-anbud

### ISSUE THREAD

**Issue by AndersTornqvist** [elegnamnden/technical-framework#5]
Comfact får frekvent frågor från export företag som vill lämna anbud på projekt i annat EU land. De behöver vid dessa anbud ett kvalificerat certifikat, dels för åtkomst, men främst för underskrift av anbud. Vi känner frustration att vi inte kan assistera dessa svenska exportföretag i hur de skall gå till väga för att vara kvalificerade i upphandlingen. Risken är att svenska konkurrenskrfatioga anbud avvisas pga. formalia/process.

En fråga till Nämnden är därför vad vi skall svara svenska exportföretag som måste lämna elektroniska anbud?

En annan tanke är om vi/ni kan tillhandahålla en tillfällig lösning så att vi inte förlorar mer exportinkomster?

**Comment by martin-lindstrom** [comment]
Tanken med detta forum är att vi ska diskutera vidareutveckling av Tekniskt ramverk. Detta inlägg är lite off-topic, men det visar att det finns ett behov av allmänna forum. Vidarebefordrar frågan samt behovet av generella fråge- och diskussionsforum till nämnden.

**Comment by AndersTornqvist** [comment]
OK.

**Comment by martin-lindstrom** [comment]
Vi har nu satt upp ett forum för allmänna diskussioner. Det vore toppen om du lägga in ditt inlägg på https://forum.eidasweb.se.
