### ISSUE TITLE
CEN EN 419241-1 on remote signature approved

### ISSUE THREAD

**Issue by AndersTornqvist** [elegnamnden/technical-framework#6]
"December 8th, Essen (DE), the CEN experts workgroup on protection profiles (WG17) has approved the final version of the remote signing standard part 1 (EN 419 241-1)."
"It will allow to setup a remote signature/seal system for advanced and qualified levels."

Behöver den svenska Normativa specifikationen uppdateras pga. detta? I så fall - i vilken utsträckning?

**Comment by martin-lindstrom** [comment]
Hej Anders. Vi har insett behovet av ett "riktigt" diskussionsforum så även frågor rörande tekniskt ramverk flyttar dit. Skulle du kunna posta din fråga till forum.eidasweb.se?
