### ISSUE TITLE
Konvertera allt till markdown och arbeta med PR

### ISSUE THREAD

**Issue by leifj** [elegnamnden/technical-framework#7]
Detta blir mycket enklare om vi konverterar alla specifikationer till markdown och arbetar med pull-requests direkt på texten. Då kan vi göra review av varje förslag och får en spårbarhet på allt som sagts kring varje diskussionspunkt. Förslagsvis använder vi https://github.com/cabo/kramdown-rfc2629 - dvs markdown för RFC:er och Internet-Drafts

**Comment by martin-lindstrom** [comment]
Håller med. Word-formatet är ett arv från när det var ett krav från projektledare.

**Comment by leifj** [comment]
http://www.writage.com/ - bara å göra save-as!

Skickat från min iPhone

**Comment by Razumain** [comment]
Save as Markdown finns inte i min Word. Varken Mac eller Windows versionen, men den här tjänsten fungerar faktiskt med väldigt bra resultat: https://word-to-markdown.herokuapp.com

**Comment by leifj** [comment]
Precis - installera http://www.writage.com/ så får du den plugin:en

**Comment by Razumain** [comment]
Har tittar på den och gillar inte. Möjligtvis för att konvertera till markdown, men inte som editor. Den hittar på för mycket eget och ändrar friskt. För lite kontroll. Vad gäller konvertering till MD så använder den ändå Pandoc. Så jag föredrar nog att köra Pandoc direkt (som inte kräver Windows)
Som editor föredrar jag just nu Oxygen 18.1 som har markdown support. Full kontroll och real time preview. Output funkar bra på Github med.

**Comment by leifj** [comment]
Konvertera på!

Skickat från min iPhone
